workflows:
  android-workflow:
    name: TezDrop Android Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Extract and build
        script: |
          unzip tezdrop_flutter.zip
          cd tezdrop
          flutter pub get
          flutter build apk --debug
    artifacts:
      - tezdrop/build/app/outputs/flutter-apk/*.apk
